/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jul 03 18:51:03 ART 2018
 */

package weak_and_det;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class BitChromosome_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  @SuppressWarnings("unused")
  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BitChromosome_ESTest_scaffolding.class.getClassLoader() ,
      "ejercicio1.es.unileon.rnag.cubiga.datatypes.ListVector",
      "ejercicio1.es.unileon.rnag.cubiga.gen.Gen",
      "ejercicio1.es.unileon.rnag.cubiga.chromosome.Chromosome",
      "ejercicio1.es.unileon.rnag.cubiga.datatypes.List",
      "ejercicio1.es.unileon.rnag.cubiga.gen.ListGen",
      "ejercicio1.es.unileon.rnag.cubiga.gen.BitGen",
      "ejercicio1.es.unileon.rnag.cubiga.datatypes.BitVector",
      "ejercicio1.es.unileon.rnag.cubiga.gen.RangeGen",
      "ejercicio1.es.unileon.rnag.cubiga.datatypes.GeneticType",
      "ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome",
      "ejercicio1.es.unileon.rnag.cubiga.chromosome.ListChromosome"
    );
  } 
}
