/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 03 21:02:00 GMT 2018
 */

package no_weak_and_prop;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome;
import ejercicio1.es.unileon.rnag.cubiga.chromosome.Chromosome;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.BitVector;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.GeneticType;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.List;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.ListVector;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.Range;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.RangeVector;
import ejercicio1.es.unileon.rnag.cubiga.gen.Gen;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class BitChromosome_ESTest extends BitChromosome_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1738, bitVector0);
      bitChromosome0.mutateGen(0);
      assertEquals(1738, bitChromosome0.length());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      List[] listArray0 = new List[3];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(934, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen((Gen) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1280, bitVector0);
      Gen gen0 = bitVector0.generateGen(0);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen(gen0, 1280);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1280
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      List[] listArray0 = new List[7];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice((Gen[]) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      Gen gen0 = bitVector0.generateGen(0);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      Gen[] genArray0 = new Gen[2];
      genArray0[0] = gen0;
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice(genArray0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      List[] listArray0 = new List[7];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1866, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(7);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.datatypes.ListVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(3671, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen(3671);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3671
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      List[] listArray0 = new List[7];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1438, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getChromosomeSlice(0, (-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.getChromosomeSlice((-896), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -896
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

@SuppressWarnings("unused")
@Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BitChromosome bitChromosome0 = null;
      try {
        bitChromosome0 = new BitChromosome((BitChromosome) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      List[] listArray0 = new List[1];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, listVector0);
      Gen[] genArray0 = new Gen[7];
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice(genArray0, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The selected slice does not fit in the position of the chromosome
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.getChromosomeSlice(0, 2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Index to be retrieved for this chromosome is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      bitChromosome0.iterator();
      assertEquals(1, bitChromosome0.length());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Range[] rangeArray0 = new Range[2];
      Range range0 = new Range(0, 0);
      rangeArray0[0] = range0;
      RangeVector rangeVector0 = new RangeVector(rangeArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, rangeVector0);
      Gen gen0 = rangeVector0.generateGen(0);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen(gen0, (-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Range[] rangeArray0 = new Range[2];
      Range range0 = new Range(0, 0);
      rangeArray0[0] = range0;
      RangeVector rangeVector0 = new RangeVector(rangeArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, rangeVector0);
      Gen gen0 = rangeVector0.generateGen(0);
      bitChromosome0.setGen(gen0, 0);
      assertEquals(1, bitChromosome0.length());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Range[] rangeArray0 = new Range[1];
      RangeVector rangeVector0 = new RangeVector(rangeArray0);
      BitChromosome bitChromosome0 = new BitChromosome(2, rangeVector0);
      Gen gen0 = bitChromosome0.getGen(0);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen(gen0, 3);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen(2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Range[] rangeArray0 = new Range[2];
      RangeVector rangeVector0 = new RangeVector(rangeArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, rangeVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Range[] rangeArray0 = new Range[2];
      RangeVector rangeVector0 = new RangeVector(rangeArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, rangeVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.datatypes.RangeVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @SuppressWarnings("unused")
  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      List[] listArray0 = new List[5];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = null;
      try {
        bitChromosome0 = new BitChromosome(0, listVector0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // BitChromosome must have a longitude greater than 0.
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      Chromosome chromosome0 = bitChromosome0.copyChromosome();
      assertEquals(1, chromosome0.length());
  }
}
