/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 01 18:29:46 ART 2018
 */

package version_final;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome;
import ejercicio1.es.unileon.rnag.cubiga.chromosome.Chromosome;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.BitVector;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.GeneticType;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.List;
import ejercicio1.es.unileon.rnag.cubiga.datatypes.ListVector;
import ejercicio1.es.unileon.rnag.cubiga.gen.Gen;
import ejercicio1.es.unileon.rnag.cubiga.gen.ListGen;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class BitChromosome_ESTest_NoRepOk extends BitChromosome_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(2, (GeneticType) null);
      BitChromosome bitChromosome1 = new BitChromosome(bitChromosome0);
      assertEquals(2, bitChromosome1.length());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      bitChromosome0.mutateGen(0);
      assertEquals(1, bitChromosome0.length());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen((Gen) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(951, bitVector0);
      Gen gen0 = bitChromosome0.getGen(0);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen(gen0, 951);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 951
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      Gen[] genArray0 = new Gen[1];
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice(genArray0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      Gen[] genArray0 = new Gen[1];
      ListGen listGen0 = new ListGen("", bitVector0);
      genArray0[0] = (Gen) listGen0;
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice(genArray0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1440, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen(1440);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1440
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      Chromosome chromosome0 = bitVector0.generateChromosome();
      // Undeclared exception!
      try { 
        chromosome0.getChromosomeSlice(0, (-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      List[] listArray0 = new List[1];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(129, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getChromosomeSlice((-449), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -449
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BitChromosome bitChromosome0 = null;
      try {
        bitChromosome0 = new BitChromosome((BitChromosome) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      Gen[] genArray0 = new Gen[1];
      // Undeclared exception!
      try { 
        bitChromosome0.setChromosomeSlice(genArray0, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The selected slice does not fit in the position of the chromosome
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      BitChromosome bitChromosome0 = new BitChromosome(1, bitVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getChromosomeSlice(0, 2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Index to be retrieved for this chromosome is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      Chromosome chromosome0 = bitVector0.generateChromosome();
      chromosome0.iterator();
      assertEquals(1, chromosome0.length());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      Chromosome chromosome0 = bitVector0.generateChromosome();
      Gen gen0 = bitVector0.generateGen(0);
      // Undeclared exception!
      try { 
        chromosome0.setGen(gen0, (-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      ListGen listGen0 = new ListGen("", (GeneticType) null);
      bitChromosome0.setGen(listGen0, 0);
      assertEquals(1, bitChromosome0.length());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.setGen((Gen) null, 2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      List[] listArray0 = new List[9];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(1, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.getGen(2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      List[] listArray0 = new List[8];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BitChromosome bitChromosome0 = new BitChromosome(2531, (GeneticType) null);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      List[] listArray0 = new List[6];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = new BitChromosome(1, listVector0);
      // Undeclared exception!
      try { 
        bitChromosome0.mutateGen(2);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // The index passed is out of bounds
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      List[] listArray0 = new List[7];
      ListVector listVector0 = new ListVector(listArray0);
      BitChromosome bitChromosome0 = null;
      try {
        bitChromosome0 = new BitChromosome(0, listVector0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // BitChromosome must have a longitude greater than 0.
         //
         verifyException("ejercicio1.es.unileon.rnag.cubiga.chromosome.BitChromosome", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BitVector bitVector0 = new BitVector(1);
      Chromosome chromosome0 = bitVector0.generateChromosome();
      Chromosome chromosome1 = chromosome0.copyChromosome();
      assertEquals(1, chromosome1.length());
  }
}
